services:
  katlhula:
    image: katlhula
    container_name: katlhula-app
    ports:
      - "8080:8080"
    depends_on:
      - katlhula-db
  katlhula-db:
    image: mysql:8.0.40
    container_name: katlhula-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: M3lodic@1
      MYSQL_ALLOW_EMPTY_PASSWORD: no
      MYSQL_RANDOM_ROOT_PASSWORD: no
      MYSQL_DATABASE: katlhula_dev
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
